theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
title: <p align="center">PHAT Nguyen</p>
logo: "/assets/img/logo.png?raw=true"
description: <b>Embedded Firmware/Software</b>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  
  <br>
  <i style="font-size:18px;" class="fa fa-map-marker"> Vietnam</i>
  <br>
  
  <br>
  <i style="font-size:18px;color:#4485e0" class="fa fa-envelope"></i>
  <a href="mailto:phat.nt@hotmail.com">Email</a>
  
  <br>
  <i style="font-size:18px;color:black" class="fa fa-github"></i>
  <a href="https://github.com/pnt325" target="_blank">Github</a>
  
  <br>
  <i style="font-size:18px;color:#0077b5" class="fa fa-linkedin"></i>
  <a href="https://www.linkedin.com/in/phatnt/">Linkedin</a>
  
  <br>
  <i style="font-size:18px;color:red" class="fa fa-youtube"></i>
  <a href="https://www.youtube.com/c/PhatNguyenDIY" target="_blank">Youtube</a>

  <br>
  <i style="font-size:18px;color:#4267B2" class="fa fa-facebook"></i>
  <a href="https://www.facebook.com/phatnt325" target="_blank">Facebook</a>

relative_links:
  enabled:     true
  collections: false
